name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: cd python/; zip -r bundle.zip .; mv bundle.zip ../; cd ..; zip bundle.zip code/* objects/* __init__.py lambda_function.py
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-north-1
          function_name: FlatScan
          zip_file: bundle.zip
